export const userClientFakeData = [
    {
      id: "615193a4c7e1363df77b9929",
      name: "Ivan Rodriguez Hernandez",
      ncliente: "1",
      company: "Tesla",
      avatar: "/static/avatar/001-man.svg",
      verified: "Yes",
      address: "Villahermosa, Tabasco, Mexico",
      project: "Project X",
    },
    {
      id: "615193bab7b256189c6fe997",
      name: "Rodrigo Alvarez Leon",
      ncliente: "2",
      company: "Ford",
      avatar: "/static/avatar/003-boy.svg",
      verified: "Yes",
      address: "Villahermosa, Tabasco, Mexico",
      project: "Project X",
    },
    {
      id: "615193d64696d4665abb8ea5",
      name: "Harry Hernandez Arias",
      ncliente: "3",
      company: "Tesla",
      avatar: "/static/avatar/011-man-2.svg",
      verified: "Yes",
      address: "Villahermosa, Tabasco, Mexico",
      project: "Project X",
    },
    {
        id: "615193d64696d4665abb8ea4",
        name: "Leonardo Daniel",
        ncliente: "4",
        company: "Tesla",
        avatar: "/static/avatar/011-man-2.svg",
        verified: "Yes",
        address: "Villahermosa, Tabasco, Mexico",
        project: "Project X",
      },
      {
        id: "615193d64696d4665abb8ea7",
        name: "Daniel Enrique Sanchez",
        ncliente: "5",
        company: "Tesla",
        avatar: "/static/avatar/011-man-2.svg",
        verified: "Yes",
        address: "Villahermosa, Tabasco, Mexico",
        project: "Project X",
      },
  ];
  